# determinant

- _determinant(aSequence)_

Answer the determinant of a square matrix.

The determinant of a _3×3_ `Integer` matrix:

```
>>> [1 2 3; 4 5 6; 7 8 9].determinant
0

>>> [1 2 4; 5 4 5; 9 2 7].determinant
-66

>>> [-2 -1 2; 2 1 4; -3 3 -1].determinant
54
```

The determinant of a _3×3_ `SmallFloat` matrix:

```
>>> [1.7 7.1 -2.7; 2.2 8.7 3.2; 3.2 -9.2 1.2].determinant
251.572
```

Determinant of a _3×3_ `Complex` matrix:

```
>>> [1j1 2j0 3j-2; 0j0 12.56637j0 0j5; 3j0 0j0 6j0].determinant
-37.6991j180.79644
```

An `identityMatrix` always has unit determinant:

```
>>> 2.identityMatrix.determinant
1

>>> 3.identityMatrix.determinant
1
```

Use to find area of a parallelogram spanned by _(1, 4)_ and _(-5, 2)_:

```
>>> [1 4; -5 2].determinant.abs
22
```

Use to find the volume of a parallelepiped:

```
>>> [1 4 3; -2 -5 2; -1 2 -2].determinant.abs
45
```

Find the area of the image of the unit disk under the linear transformation associated to a matrix:

```
>>> let m = [7 -3; 5 7; -10 4];
>>> m.transposed.dot(m).determinant.sqrt * pi
10 * 122.sqrt * pi
```

Determine whether the following basis for _R ^3_ is right-handed:

```
>>> [1 0 1; 0 1 1; 1 0 0].determinant
-1
```

The determinant of the transpose of _m_ equals the determinant of _m_:

```
>>> let m = 0.randomFloat(1, [3 3]);
>>> m.transposed.determinant
m.determinant
```

The determinant is a multiplicative map,
ie. the determinant of a matrix product equals the product of their determinants:

```
>>> let a = 0.randomFloat(1, [3 3]);
>>> let b = 0.randomFloat(1, [3 3]);
>>> a.dot(b).determinant
a.determinant * b.determinant
```

The determinant is the signed volume of the parallelepiped generated by its rows:

```
>>> [1 2 3; -1 1 0; 3 2 1].determinant
12
```

A square matrix has an inverse if and only if its determinant is nonzero:

```
>>> [1 2 1; 1 0 2; -1 2 -3].determinant
0
```

* * *

See also: isSquareMatrix

References:
_Mathematica_
[1](https://mathworld.wolfram.com/Determinant.html)
[2](https://reference.wolfram.com/language/ref/Det.html),
_W_
[1](https://en.wikipedia.org/wiki/Determinant)
