# File

- _File([b₁ b₂ …], n, o)_

`File` is a `Type` representing a file system object.
Ordinarily these values are generated by the system.

The `File` method requires a list of byte arrays _b_,
a file name string _n_,
and a options record _o_.

`File` implements the `BinaryLargeObject` trait,
and in addition implements the methods `lastModified` and `name`.

```
>>> let x = File(
>>> 	[ByteArray(1:9)],
>>> 	'x.bin',
>>> 	(
>>> 		type:
>>> 		'application/octet-stream'
>>> 	)
>>> );
>>> (x.name, x.size, x.type)
(
	'x.bin',
	9,
	'application/octet-stream'
)
```

* * *

See also: BinaryLargeObject

Guides: File Functions

References:
_W3c_
[1](https://w3c.github.io/FileAPI/#file-section)

Categories: System, Type
