# levskayaPolyhedraCatalogue

- _levskayaPolyhedraCatalogue(aSystem)_

The Levskaya polyhedron catalogue is a collection of polyhedra generated by the Polyhedronisme program written by Anselm Levskaya.
Answers a `Record` of `Polyhedron`s, keyed by name.

Count catalogue entries,
contains the five Platonic solids and the thirteen Archimedean solids:

~~~
>>> system
>>> .levskayaPolyhedraCatalogue
>>> .size
5 + 13
~~~

Count the vertices and faces and edges of each entry:

```
>>> system
>>> .levskayaPolyhedraCatalogue
>>> .collect { :each |
>>> 	[
>>> 		each.vertexCount,
>>> 		each.faceCount,
>>> 		each.edgeCount
>>> 	]
>>> }
(
	C: [8, 6, 12],
	D: [20, 12, 30],
	I: [12, 20, 30],
	O: [6, 8, 12],
	T: [4, 4, 6],
	aC: [12, 14, 24],
	aD: [30, 32, 60],
	bC: [48, 26, 72],
	bD: [120, 62, 180],
	eC: [24, 26, 48],
	eD: [60, 62, 120],
	sC: [24, 38, 60],
	sD: [60, 92, 150],
	tC: [24, 14, 36],
	tD: [60, 32, 90],
	tI: [60, 32, 90],
	tO: [24, 14, 36],
	tT: [12, 8, 18]
)
```

A perspective drawing of the truncated icosidodecahedron:

~~~spl svg=A
system
.levskayaPolyhedraCatalogue
.at('bD')
.asPerspectiveDrawing
~~~

![](sw/spl/Help/Image/levskayaPolyhedraCatalogue-A.svg)

_Note:_
The catalogue is a `LibraryItem`,
and this function requires the item be in the interpreter cache.

* * *

See also: asPerspectiveDrawing, fradinPolhyedraCatalogue, holmesPolyhedraCatalogue, mcClurePolyhedraCatalogue, Polyhedron

Guides: Library Catalogue
