# mcClurePolyhedraCatalogue

- _mcClurePolyhedraCatalogue(system)_

The McClure polyhedron catalogue is a collection of polyhedra generated by Mark McClure for a Polyhedron unfolding notebook.
Answers a `Record` of `Polyhedron`s, keyed by name.

Count catalogue entries:

~~~
>>> system
>>> .mcClurePolyhedraCatalogue
>>> .size
154
~~~

Count the vertices faces and edges of each entry with 13 faces:

```
>>> system
>>> .mcClurePolyhedraCatalogue
>>> .select { :each |
>>> 	each.faceCount = 13
>>> }
>>> .keys
[
	'biaugmented pentagonal prism'
	'gyroelongated square pyramid'
]
```

A perspective drawing of Jessens orthogonal icosahedron:

~~~spl svg=A
system
.mcClurePolyhedraCatalogue
.at('Jessens orthogonal icosahedron')
.asPerspectiveDrawing
~~~

![](sw/spl/Help/Image/mcClurePolyhedraCatalogue-A.svg)

_Note:_
The catalogue is a `LibraryItem`,
and this function requires the item be in the interpreter cache.

* * *

See also: asPerspectiveDrawing, fradinPolhyedraCatalogue, holmesPolyhedraCatalogue, levskayaPolyhedraCatalogue, Polyhedron

Guides: Library Catalogue
