# recurrenceMatrix

- _recurrenceMatrix([x₁ x₂ …], e, d, m, ε)_

Answer the recurrence matrix of the vector _x_,
with embedding dimension _e_ and delay _d_,
using the distance measure _m_,
with threshold _ε_.
_m_ should be either 'Manhattan' or 'Euclidean' or 'Supremum'.

Recurrence plot of uncorrelated stochastic data,
generated by a normal distribution random variate:

~~~spl svg=A
let r = Sfc32(681472);
NormalDistribution(0, 1)
.randomVariate(r, [200])
.recurrenceMatrix(1, 1, 'Manhattan', 0.1)
.Bitmap
~~~

![](sw/spl/Help/Image/recurrenceMatrix-A.png)

Recurrence plot of a random walk:

~~~spl svg=B
let r = Sfc32(789314);
[-1 1].randomChoice(r, 200)
.prefixSum
.recurrenceMatrix(1, 1, 'Manhattan', 0.1)
.Bitmap
~~~

![](sw/spl/Help/Image/recurrenceMatrix-B.png)

Recurrence plot of a harmonic oscillation with two frequencies:

~~~spl svg=C
(0 -- 4.pi).subdivide(200).collect { :x |
	(x * 3).sin + (x * 7).sin
}.recurrenceMatrix(1, 1, 'Manhattan', 0.1)
.Bitmap
~~~

![](sw/spl/Help/Image/recurrenceMatrix-C.png)

Recurrence plot of a harmonic oscillation with two frequencies,
without thesholding:

~~~spl svg=D
(0 -- 4.pi).subdivide(200).collect { :x |
	(x * 0.7).sin + (x * 1.3).sin
}.recurrenceMatrix(1, 1, 'Manhattan')
.rescale.Graymap
~~~

![](sw/spl/Help/Image/recurrenceMatrix-D.png)

* * *

See also: Bitmap, distanceMatrix, Graymap, matrixPlot

Guides: Matrix Functions, Plotting Functions

References:
_Mathematica_
[1](https://mathworld.wolfram.com/RecurrencePlot.html),
_W_
[1](https://en.wikipedia.org/wiki/Recurrence_plot)

Further Reading: Eckmann 1987
