# schareinKnotCatalogue

- _schareinKnotCatalogue(aSystem)_

The Scharein knot catalogue is a collection of knot geometries from the Knot Server at the Simon Fraser University,
generated by the Knot Plot program by Robert Scharein.
Answers a `Record` of matrices, keyed by name.
The names are those given in the Rolfsen Knot Table.

A knot is an embedding of the circle into three-dimensional Euclidean space.
Each knot is a matrix of three columns, _x_, _y_ and _z_.

Count the number of entries:

```
>>> system.schareinKnotCatalogue.size
250
```

Draw the entry for the knot _8-1_,
the first eight crossing knot in the catalogue,
using an _xy_ projection:

~~~spl svg=A
system
.schareinKnotCatalogue
.at('8-1')
.columns(1:2)
.asLineDrawing
~~~

![](sw/spl/Help/Image/schareinKnotCatalogue-A.svg)

A perspective drawing of the entry for the knot _9-37_:

~~~spl svg=B
system
.schareinKnotCatalogue
.at('9-37')
.Polygon
.asPerspectiveDrawing
~~~

![](sw/spl/Help/Image/schareinKnotCatalogue-B.svg)

_Note:_
The catalogue is a `LibraryItem`,
and this function requires the item be in the interpreter cache.

The `schareinKnotCatalogue` method is `requireLibraryItem` of 'SchareinKnotCatalogue'.

* * *

See also: Line, schareinLinkCatalogue, schareinMinimalKnotCatalogue

References:
_W_
[1](https://en.wikipedia.org/wiki/Knot_(mathematics))

Further Reading: Rolfsen 1976
