# schareinKnotCatalogue

- _schareinKnotCatalogue(aSystem)_

The Scharein knot catalogue is a collection of knot geometries from the Knot Server at the Simon Fraser University,
generated by the Knot Plot program by Robert Scharein.
Answers a `Record` of `Line`s, keyed by name.

A knot is an embedding of the circle into three-dimensional Euclidean space.

Count the number of entries:

```
>>> system.schareinKnotCatalogue.size
250
```

Draw the entry for the knot _8-1_:

~~~spl svg=A
system
.schareinKnotCatalogue
.at('8-1')
.collect { :each |
	let [x, y, z] = each;
	[x, y]
}
.asLineDrawing
~~~

![](sw/spl/Help/Image/schareinKnotCatalogue-A.svg)

_Note:_
The catalogue is a `LibraryItem`,
and this function requires the item be available locally.

The `schareinKnotCatalogue` method is `requireLibraryItem` of 'SchareinKnotCatalogue'.

* * *

See also: Line, schareinLinkCatalogue

References:
_W_
[1](https://en.wikipedia.org/wiki/Knot_(mathematics))
