# schareinLinkCatalogue

- _schareinLinkCatalogue(aSystem)_

The Scharein knot catalogue is a collection of knot geometries from the Knot Server at the Simon Fraser University,
generated by the Knot Plot program by Robert Scharein.
Answers a `Record` of lists of `Line`s, keyed by name.

A link is a collection of knots which do not intersect,
but which may be linked (or knotted) together.

Count the number of entries:

```
>>> system.schareinLinkCatalogue.size
130
```

Draw the entry for the knot _8-2-13_:

~~~spl svg=A
system
.schareinLinkCatalogue
.at('8-2-13')
.collect { :each |
	each.collect { :c |
		let [x, y, z] = c;
		[x, y]
	}
}
.LineDrawing
~~~

![](sw/spl/Help/Image/schareinLinkCatalogue-A.svg)

_Note:_
The catalogue is a `LibraryItem`,
and this function requires the item be available locally.

The `schareinLinkCatalogue` method is `requireLibraryItem` of 'SchareinLinkCatalogue'.

* * *

See also: Line, schareinKnotCatalogue

References:
_W_
[1](https://en.wikipedia.org/wiki/Link_(knot_theory))
[2](https://en.wikipedia.org/wiki/Knot_(mathematics))
