[
	Package('Benchmark-Benchmark'),
	Package('Benchmark-SomRandom'),
	Package('Benchmark-Bounce'),
	Package('Benchmark-List'),
	Package('Benchmark-Permute'),
	Package('Benchmark-Queens'),
	Package('Benchmark-Sieve'),
	Package('Benchmark-Storage'),
	Package('Benchmark-Towers'),
	Package('Benchmark-Havlak'),
	Package('Benchmark-Json'),
	Package('Benchmark-Mandelbrot'),
	Package('Benchmark-NBody')
].loadPackages
