loadSequence([
	'kernel/Object.sl',
	'kernel/Boolean.sl',
	'kernel/Method.sl',
	'kernel/Procedure.sl',
	'kernel/UndefinedObject.sl',
	'lib/col/ArrayedCollection.sl',
	'lib/col/Collection.sl',
	'lib/col/SequenceableCollection.sl',
	'lib/col/Array.sl',
	'lib/col/String.sl',
	'lib/num/Binary.sl',
	'lib/num/Integral.sl',
	'lib/num/Magnitude.sl',
	'lib/num/Numeric.sl',
	'lib/num/Number.sl'
])
