loadSequence([
	'kernel/ArrayedCollection.sl',
	'kernel/Collection.sl',
	'kernel/Dictionary.sl',
	'kernel/Magnitude.sl',
	'kernel/Numeric.sl',
	'kernel/SequenceableCollection.sl',
	'kernel/Array.sl',
	'kernel/Boolean.sl',
	'kernel/Nil.sl',
	'kernel/Number.sl',
	'kernel/Object.sl',
	'kernel/Procedure.sl',
	'kernel/String.sl',
	'kernel/StringDictionary.sl',
	'kernel/Void.sl'
])
