loadSequence([
	'Collections/Cons.sl',
	'Collections/LinkedList.sl',
	'Collections/Pair.sl',
	'Collections/Streams/PositionableStream.sl',
	'Collections/Streams/ReadStream.sl',
	'Collections/Streams/WriteStream.sl',
	'Collections/StringDictionary.sl',
	'Collections/ValueLink.sl',
	'Graphics/CartesianPoint.sl',
	'Graphics/Point.sl',
	'Graphics/Rectangle.sl',
	'Numbers/LargeInteger.sl',
	'Text/RegExp.sl',
	'Time/Duration.sl'
])
