[
	Package('Music-Frequency'),
	Package('Music-JiTuning'),
	Package('Music-Pitch'),
	Package('Sound-OpenSoundControl'),
	Package('Sound-SuperCollider-Lang'),
	Package('Sound-SuperCollider-Lang-Clock'),
	Package('Sound-SuperCollider-Lang-J'),
	Package('Sound-SuperCollider-Lang-Texture'),
	Package('Sound-SuperCollider-Synth'),
	Package('Sound-SuperCollider-Synth-Bindings'),
	Package('Sound-SuperCollider-Synth-Pseudo')
].loadPackages
