[
	'Music-Frequency'
	'Music-JiTuning'
	'Music-Pitch'
	'Sound-OpenSoundControl'
	'Sound-SuperCollider-Lang'
	'Sound-SuperCollider-Lang-Clock'
	'Sound-SuperCollider-Lang-J'
	'Sound-SuperCollider-Lang-Texture'
	'Sound-SuperCollider-Synth'
	'Sound-SuperCollider-Synth-Bindings'
	'Sound-SuperCollider-Synth-Pseudo'
].collect(Package:/1).loadPackages
