[
	'Music-JiTuning'
	'Music-Pitch'
	'Protocol-OpenSoundControl'
	'SuperCollider-Lang'
	'SuperCollider-J'
	'SuperCollider-Texture'
	'SuperCollider-Synth'
	'SuperCollider-Bindings'
	'SuperCollider-Pseudo'
].collect(Package:/1).loadPackages
