[
	'Kernel.sl',
	'Collections.sl',
	'Collections/Bitset.sl',
	'Collections/Heap.sl',
	'Collections/LinkedList.sl',
	'Collections/Stream.sl',
	'Geometry.sl',
	'Graphics.sl',
	'Random.sl',
	'System.sl',
	'Time.sl',
	'Unit/Angle.sl',
	'Unit/Frequency.sl',
	'Unit/Length.sl',
	'Unit/Mass.sl',
	'Unit/SiUnit.sl'
].loadUrlSequence
