[
	Package('Character.sl'),
	Package('Complex.sl'),
	Package('Fraction.sl'),
	Package('LargeInteger.sl'),
	Package('Promise.sl'),
	Package('RegExp.sl'),
	Package('Std', [
		'Collections/ArrayBuffer.sl'
		'Collections/Association.sl'
		'Collections/Bag.sl'
		'Collections/Bitset.sl'
		'Collections/ByteArray.sl'
		'Collections/Float64Array.sl'
		'Collections/Graph.sl'
		'Collections/Heap.sl'
		'Collections/Interval.sl'
		'Collections/LinkedList.sl'
		'Collections/PriorityQueue.sl'
		'Collections/RunArray.sl'
		'Collections/SortedArray.sl'
		'Collections/Stream.sl'
		'Collections/WeakMap.sl'
		'Geometry.sl'
		'Graphics/Colour.sl'
		'RandomNumberGenerator.sl'
		'System/Method.sl'
		'System/Trait.sl'
		'System/Type.sl'
		'System/Blob.sl'
		'System/CategoryDictionary.sl'
		'System/File.sl'
		'System/LibraryItem.sl'
		'System/Response.sl'
		'System/Storage.sl'
		'System/Transcript.sl'
		'System/URL.sl'
		'System/Window.sl'
		'Time/Date.sl'
		'Time/Duration.sl'
		'Time/Frequency.sl'
		'Time/TimeStamp.sl'
		'Unit/Angle.sl'
		'Unit/Length.sl'
		'Unit/Mass.sl'
		'Unit/SiUnit.sl'
	])
].loadPackages
