# Help Index

- :/ -- arity selector syntax
- := -- assignment syntax
- -> -- associate with
- ;; -- comment
- < -- comparison operator
- <= -- comparison operator
- \>= -- comparison operator
- ++ -- concatenation
- = -- equality operator
- ~~ -- identity
- == -- identity operator
- ~= -- inequality operator
- & -- logic operator
- | -- logic operator
- % -- mathematical operator
- \* -- mathematical operator
- ^ -- mathematical operator
- \+ -- mathematical operator
- \- -- mathematical operator
- / -- mathematical operator
- :: -- quoted at syntax
- .. -- range operator syntax
- Array -- collection type
- Association -- associate with
- Boolean -- logic
- Collection -- collection trait
- Dictionary -- collection trait & type
- Duration -- time
- Fraction -- arithmetic
- Method -- behaviour type
- Number -- number type
- Object -- value trait
- Block -- behaviour type
- String -- text
- Record -- dictionary type
- System -- system
- TimeStamp -- time
- Trait -- behaviour type
- Type -- value type
- Nil -- nil type
- Void -- uninhabited type
- add -- adding
- addAll -- adding
- allButFirst -- accesing
- asArray -- converting
- ascii -- encoding
- at -- accessing
- atPut -- accessing
- atRandom -- random selection
- collect -- enumerating
- concatenation -- converting
- count -- enumerating
- cull -- evaluating
- currentTime -- time
- denominator -- arithmetic
- divisors -- arithmetic
- do -- enumerating
- error -- error handling
- false -- boolean constant
- if -- conditional evaluation
- ifFalse -- conditional evaluation
- ifNil -- conditional evaluation
- ifTrue -- conditional evaluation
- inf -- mathematical constant
- injectInto -- enumerating
- isEmpty -- testing
- isFraction -- arithmetic
- isInteger -- predicate
- isPrime -- arithmetic
- iso8601 -- time
- json -- protocol
- lines -- accessing
- map -- enumerating
- max -- testing
- nextPrime -- arithmetic
- nil -- undefined object
- not -- logical negation
- numArgs -- accessing
- numerator -- arithmetic
- ofSize -- instance creation
- parseJson -- protocol
- pi -- mathematical constant
- primeFactors -- arithmetic
- primeLimit -- arithmetic
- product -- math operator
- quotient -- arithmetic
- randomFloat -- random number generator
- randomInteger -- random number generator
- reduce -- enumerating
- reject -- enumerating
- remainder -- arithmetic
- remove -- removing
- return -- non-local control flow
- reversed -- converting
- select -- enumerating
- sign -- math operator
- size -- accessing
- sorted -- sorting
- species -- reflection
- sum -- math operator
- system -- reflection
- timesRepeat -- enumerating
- transpose -- rearranging
- true -- boolean constant
- typeOf -- reflection
- unicode -- printing
- unixTimeInMilliseconds -- time
- unlines -- accessing
- utf8 -- encoding
- value -- evaluation
- valueWithReturn -- non-local control flow
- whileFalse -- conditional evaluation
- whileTrue -- conditional evaluation
