# Trailing Dictionary Syntax

Rewrite rules:

- _f(k: v, ...) ..._ ≡ _f((k: v, ...), ...)_
- _f(x, ...) (k: v, ...) ..._ ≡ _f(x, ..., (k: v, ...), ...)_
- _x.f (k: v, ...) ..._ ≡ _f(x, (k: v, ...), ...)_
- _x.f(y, ...) { p }..._ ≡ _f(x, y, ..., (k: v, ...), ...)_

Trailing dictionary syntax allows any number of concluding _literal dictionary_ arguments to be written outside the parameter list.
This notation is particularly clear for procedures that accept an _options_ dictionary.

The program below generates a simple texture, chords are generated by frequency shifting a sine tone.
The dictionary form of the Ugen constructors _SinOsc_ and _FreqShift_ are used to label each parameter.

	{
		var oct = [36, 48, 60].atRandom;
		var note = [0, 2, 4, 5, 7, 9, 11].atRandom;
		var freq = (oct + note).midiCps;
		var osc = SinOsc(freq: freq, phase: 0) * 0.1;
		var left = osc + FreqShift(
			in: osc,
			freq: freq * 1.5,
			phase: 0
		);
		var right = FreqShift(
			in: left,
			freq: SinOsc(freq: 3.23, phase: 0) * 5,
			phase: 0
		);
		[left, right] / 3
	}.overlap(3, 3, 3)

* * *

See also: [Trailing Procedure Syntax]
