spl-repl-core:
	./spl replPerLine --strict

spl-repl:
	./spl replPerLine StandardLibrary --strict

spl-repl-non-strict:
	./spl replPerLine StandardLibrary

spl-repl-unsafe:
	./spl replPerLine --unsafe

spl-repl-verbose:
	./spl replPerLine StandardLibrary --strict --verbose

spl-repl-bm:
	./spl replPerLine StandardLibrary BenchmarkLibrary --strict

spl-repl-bm-unsafe:
	./spl replPerLine StandardLibrary BenchmarkLibrary --unsafe

spl-repl-sc:
	./spl replPerLine StandardLibrary SuperColliderLibrary --strict

spl-repl-ui:
	./spl replPerLine StandardLibrary SuperColliderLibrary SmallKansasLibrary --strict

spl-server:
	./spl sc tcpServer --port=3010
