#!/bin/sh
export SplDirectory=$HOME/sw/spl
rlwrap --always-readline deno run --allow-read --allow-env --allow-net --allow-run --allow-write --unstable $SplDirectory/ts/cli.ts --dir=$SplDirectory "$@"
