[

	/* Navigator */
	'DocumentObjectModel'
	'NavigatorMidi'
	'NavigatorSvg'

	/* SmallKansas */
	'UserEventTarget'
	'View'
	'SmallKansas'
	'ColumnBrowser'
	'Frame'
	'ListChooser'
	'Menu'
	'SmallProgram'
	'TextEditor'
	'TextElement'

	/* SmallKansans */
	'AnalogueClock'
	'CategoryBrowser'
	'ColourChooser'
	'CrystalStructureBrowser'
	'CrystalStructureOracle'
	'DigitalClock'
	'HelpBrowser'
	'HelpFileViewer'
	'HelpTextViewer'
	'ImageViewer'
	'Inspector'
	'MethodBrowser'
	'MethodSignatureBrowser'
	'MidiMonitorMenu'
	'MidiPortBrowser'
	'Notebook'
	'PackageBrowser'
	'PackageIndexBrowser'
	'PngViewer'
	'ScalaJiMetaBrowser'
	'ScalaJiTuningBrowser'
	'ScalaScaleBrowser'
	'SuperColliderProgramBrowser'
	'SuperColliderProgramOracle'
	'SuperColliderSynthesiserStatusMonitor'
	'SvgViewer'
	'SystemBrowser'
	'TableViewer'
	'TraitBrowser'
	'TranscriptViewer'
	'TypeBrowser'
	'WindowMenu'
	'Workspace'
	'WorldMenu'
].primitiveLoadPackageSequence.then { :unused |
	system.smallKansas
}
